### ISSUE TITLE
Histogram switching to per week failed

### ISSUE THREAD

**Issue by longshuicy** [ncsa/standalone-smm-analytics#60]
{"ERROR":{"message":"An error occurred (404) when calling the HeadObject operation: Not Found","traceback":"Traceback (most recent call last):\n  File \"./rabbitmq_handler.py\", line 25, in rabbitmq_handler\n    s3.downloadToDisk(filename=filename, localpath=localPath, remotepath=remotePath)\n  File \"/scripts/writeToS3.py\", line 47, in downloadToDisk\n    os.path.join(remotepath, filename), f)\n  File \"/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py\", line 795, in download_fileobj\n    return future.result()\n  File \"/usr/local/lib/python3.7/site-packages/s3transfer/futures.py\", line 103, in result\n    return self._coordinator.result()\n  File \"/usr/local/lib/python3.7/site-packages/s3transfer/futures.py\", line 266, in result\n    raise self._exception\n  File \"/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py\", line 269, in _main\n    self._submit(transfer_future=transfer_future, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/s3transfer/download.py\", line 357, in _submit\n    **transfer_future.meta.call_args.extra_args,\n  File \"/usr/local/lib/python3.7/site-packages/botocore/client.py\", line 530, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/botocore/client.py\", line 960, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found\n"}}

When switching tp "per week" for Reddit post it didn't work.

**Comment by ywkim312** [comment]
I have tested in smile.smm.ncsa.illinois.edu site with reddit and per week worked. And all others worked as well. Could you test one more time? 
![image](https://github.com/ncsa/standalone-smm-analytics/assets/12547573/bc2ec904-8e27-42ef-af8b-3fc3b9d2fb22)

**Comment by longshuicy** [comment]
can't reproduce. Close for now.
